from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import BookList, BookViewSet

# Create the router from CRUD operations
router = DefaultRouter()
router.register(r'books_all', BookViewSet, basename='book_all')

urlpatterns = [
    # route for listing books (ListAPIView)
    path('books/', BookList.as_view(), name='book-list'),

    # routes generated by the router for CRUD
    path('', include(router.urls)),
]
